name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          DOCKER_BUILDKIT=1 docker build -t local/smp-server --build-arg APP="smp-server" --build-arg APP_PORT="5223" . # For xmp-server
          DOCKER_BUILDKIT=1 docker build -t local/xftp-server --build-arg APP="xftp-server" --build-arg APP_PORT="443" . # For xftp-server
      - name: Start docker
        shell: bash
        run: |
          docker run -d \
          -e "ADDR=radio.rontti.org" \
          -e "PASS=Dpp31415926!" \
          -p 5223:5223 \
          -v $HOME/simplex/smp/config:/etc/opt/simplex:z \
          -v $HOME/simplex/smp/logs:/var/opt/simplex:z \
          local/smp-server
